site_name: "Repositorio de Prácticas"
repo_url: "https://github.com/falclop"
theme:
  name: "material"
  palette:
    primary: teal
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - Inicio: index.md
  - Prácticas:
      - "Practica 1.7 - WordPress con WP-CLI": p17.md
      - "Practica 1.11 - Infraestructura 3 niveles con Bash": p111.md
      - "Practica 3.2 - IaaC con Ansible": p32.md
      - "Practica 4.5 - Terraform": p45.md
      - "Practica 5.2 - WordPress Dockerizado": p52.md
      - "Practica 5.4 - Dockerizar Imagen": p54.md
      - "Practica 8.1 - Hosting Compartido PLESK": p8.md
  - Acerca de: about.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji