site_name: "Repositorio de Prácticas de Falclop"
repo_url: "https://github.com/falclop"
theme:
  name: "material"
  palette:
    primary: teal
  font:
    text: Open Sans
  language: es

  features:
    # Carga instantánea
    - navigation.instant
    # Ancla de navegación para contenido
    - navigation.tracking
    # Menus extendibles
    - navigation.expand
    # Barra de búsqueda
    - search.suggest
    - search.highlight
    # Cabecera se esconde al scrollear
    - header.autohide
    - navigation.footer
  
  extra:
    - icon: fontawesome/brands/github
      link: https://github.com/falclop
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fabianalcaidelopez1991/

nav:
  - Inicio: index.md
  - Prácticas:
      - "Practica 1.7 - WordPress con WP-CLI": p17.md
      - "Practica 1.11 - Infraestructura 3 niveles con Bash": p111.md
      - "Practica 3.2 - IaaC con Ansible": p32.md
      - "Practica 4.5 - Terraform": p45.md
      - "Practica 5.2 - WordPress Dockerizado": p52.md
      - "Practica 5.4 - Dockerizar Imagen": p54.md
      - "Practica 8.1 - Hosting Compartido PLESK": p8.md

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji